plugins:
  - jekyll-seo-tag

title: KAPSARC Toolkit for Behavioral Analysis
author: King Abdullah Petroleum Studies and Research Center
description: bargaining, negotiation, mathematical model, simulation model, agent-based model, analytical politics, political science, behavioral analysis, KTAB, KAPSARC, political modeling, decision-making, CDMP, policy modeling, policy analysis, spatial model, economic model, economics, politics, computer science
